---

- name: ensure all needed folders exist
  file: path="{{ sphinx_folder }}/{{ item }}" state=directory
  with_items:
    - src

- name: get sphinx source
  unarchive:
    src: https://sphinxsearch.com/files/sphinx-{{ sphinx_version }}-release.tar.gz
    dest: "{{ sphinx_folder }}/src"
    remote_src: yes

- name: compile and install sphinx
  shell: "{{ item }}"
  with_items:
    - "./configure --prefix={{ sphinx_folder }}"
    - "make"
    - "make install"
  args:
    chdir: "{{ sphinx_folder }}/src/sphinx-{{ sphinx_version }}-release"