---
- name: Install my favorite tools on all my account
  hosts: myEthersys-hosting
  roles:
    - role: hst-bin
    - role: hst-logrotate

- name: Install specific Tools for my Wordpress hosting
  hosts: myEthersys-Wordpress
  roles:
    - role: hst-wpcli

- name: Install my favorite tools on all my account!
  hosts: myEthersys-Redmine
  roles:
    - role: hst-ruby
