---
- name: get authorized loopback interface
  command: python -c 'from socket import inet_ntoa; from struct import pack; from pwd import getpwuid; from os import getuid; print(inet_ntoa(pack("!L", 0x7f000000 | getpwuid( getuid() ).pw_gid)))'
  register: loopback_output

- name: register loopback interface adress as fact
  set_fact: loopback_adress={{ loopback_output.stdout }}

- name: add local env variable to easily retrieve authorized loopback interface value
  lineinfile:
    create: yes
    dest: ~/.bash_profile
    line: export LOCALSERVER={{ loopback_output.stdout }}
