python_version: 2.7.12
airflow_name: airflow-{{ ansible_user }}
airflow_version: 1.8.0
airflow_data_folder: airflow
airflow_folder: "/home/{{ ansible_user }}/.virtualenvs/airflow/"
airflow_hostname: "{{ ansible_user }}.occitech.eu"
airflow_port: 8088
airflow_meso_port: 5050
airflow_statsd_port: 8125
airflow_scheduler_env: AIRFLOW_HOME="/home/{{ ansible_user }}/airflow",HOME="/home/{{ ansible_user }}",VIRTUAL_ENV="/home/{{ ansible_user }}/.virtualenvs/airflow",PATH="/home/{{ ansible_user }}/.virtualenvs/airflow/bin:$%(ENV_PATH)s"
