python_version: 2.7.16
airflow_name: airflow-{{ ansible_user }}
airflow_version: 1.10.0
airflow_data_folder: airflow
airflow_log_folder: "{{ airflow_data_folder }}"
airflow_folder: "/home/{{ ansible_user }}/airflow/"
airflow_hostname: "{{ ansible_user }}.ethersys.host"
airflow_port: 8088
airflow_meso_port: 5050
airflow_statsd_port: 8125
airflow_tmpdir: "/home/{{ ansible_user }}/admin/tmp"
airflow_webserver_env: TMPDIR="{{ airflow_tmpdir }}",PYTHON_VERSION="{{ python_version }}",AIRFLOW_HOME="/home/{{ ansible_user }}/{{ airflow_data_folder }}",HOME="/home/{{ ansible_user }}",PATH="/home/{{ ansible_user }}/bin/:/home/{{ ansible_user }}/.local/bin:/usr/local/bin:/usr/bin:/bin"
airflow_scheduler_env: TMPDIR="{{ airflow_tmpdir }}",PYTHON_VERSION="{{ python_version }}",AIRFLOW_HOME="/home/{{ ansible_user }}/airflow",HOME="/home/{{ ansible_user }}",PATH="/home/{{ ansible_user }}/bin/:/home/{{ ansible_user }}/.local/bin:/usr/local/bin:/usr/bin:/bin"