---
- pause:
    prompt: "Enter database name, press (ctrl+c) and then (c) after:"
  register: prompt_dbname
  when: magento_dbname is not defined

- set_fact:
    magento_dbname: "{{ prompt_dbname.user_input }}"
  when: magento_dbname is not defined

- pause:
    prompt: "Enter database user, press (ctrl+c) and then (c) after:"
  register: prompt_dbuser
  when: magento_dbuser is not defined

- set_fact:
    magento_dbuser: "{{ prompt_dbuser.user_input }}"
  when: magento_dbuser is not defined

- pause:
    prompt: "Enter database pass, press (ctrl+c) and then (c) after:"
  register: prompt_dbpass
  when: magento_dbpass is not defined

- set_fact:
    magento_dbpass: "{{ prompt_dbpass.user_input }}"
  when: magento_dbpass is not defined

- name: delete previous install directory
  file: path={{ magento_folder }} state=absent

- name: create install directory
  file: path={{ magento_folder }} state=directory

- name: configure access to database for mysql tools
  template: src=.my.cnf.j2  dest=~/.my_{{ magento_dbname }}.cnf

- name: flush MySQL database
  command: mysql --defaults-extra-file=~/.my_{{ magento_dbname }}.cnf -e "drop database {{ magento_dbname }}; create database {{ magento_dbname }};"

- name: set magerun config
  template: src=n98-magerun.yaml.j2 dest=/home/{{ ansible_user }}/.n98-magerun.yaml

- name: install Magento
  shell: php -d memory_limit=1024M /home/{{ ansible_user }}/bin/n98-magerun install --magentoVersion={{ magento_version }} --installationFolder={{ magento_folder }} --dbHost={{ magento_dbhost }} --dbUser={{ magento_dbuser }} --dbName={{ magento_dbname }} --dbPass={{ magento_dbpass }} --baseUrl={{ magento_baseurl }} --no-interaction
