---
- name: ensure needed folders exist
  file: path=~/redis/{{ redis_name }}/{{ item }} state=directory
  with_items:
    - log
    - etc
    - data

- name: Download and extract Redis
  unarchive:
    src: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
    dest: ~/redis/{{ redis_name }}/
    remote_src: True

- name: compile Redis
  command: chdir=~/redis/{{ redis_name }}/redis-{{ redis_version }}/ make

- name: link Redis binaries
  file:
    src: '/home/{{ ansible_user }}/redis/{{ redis_name }}/redis-{{ redis_version }}/src/{{ item }}'
    dest: '~/bin/{{ item }}'
    state: link
  with_items:
    - redis-server
    - redis-cli

- name: send Redis config
  template:
    src:  redis.conf.j2
    dest: ~/redis/{{ redis_name }}/etc/redis.conf

- name: install Redis PHP extension
  command: ad_install_pecl redis {{redis_php_extension}}

- name: send Supervisor config
  template:
    src:  supervisor.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ redis_name }}.conf"

- name: reload Supervisor config to launch Redis
  command: "{{ supervisor_bin }}/supervisorctl update"
