---
- name: ensure needed folders exist
  file: path=~/redis/{{ redis_name }}/{{ item }} state=directory
  with_items:
    - log
    - etc
    - data

- name: send Redis config
  template:
    src:  redis.conf.j2
    dest: ~/redis/{{ redis_name }}/etc/redis.conf

- name: install Redis PHP extension
  command: ad_install_pecl redis

- name: send Supervisor config
  template:
    src:  supervisor.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ redis_name }}.conf"

- name: reload Supervisor config to launch Redis
  command: /home/{{ ansible_user }}/python/builds/{{ python_version }}/bin/supervisorctl update
