---
- name: ensure all airflow folders exist
  file: path="{{ item }}" state=directory follow=yes
  with_items:
    - "{{ airflow_folder }}"
    - "/home/{{ ansible_user }}/{{ airflow_data_folder }}"
    - "/home/{{ ansible_user }}/{{ airflow_log_folder }}"

- name: send Airflow config
  template:
    src:  airflow.cfg.j2
    dest: /home/{{ ansible_user }}/{{ airflow_data_folder }}/airflow.cfg
    force: no

- name: register airflow bin path
  set_fact:
    airflow_bin: /home/{{ ansible_user }}/.local/bin

- name: install and init airflow
  shell: chdir=/home/{{ ansible_user }}/{{ airflow_data_folder }} source ~/.bash_profile; {{ item }}
  with_items:
    - pip install MySQL-python
    - pip install airflow=={{ airflow_version }}
    - pip install airflow[hive]=={{ airflow_version }}
    - airflow initdb
  args:
     executable: /bin/bash
  environment:
    PATH: /home/{{ ansible_user }}/.local/bin:{{ ansible_env.PATH }}
    AIRFLOW_HOME: /home/{{ ansible_user }}/{{ airflow_data_folder }}
    PYTHON_VERSION: 2.7.12

- name: send Supervisor config
  template:
    src:  supervisor.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ airflow_name }}.conf"

- name: reload Supervisor config to launch Supervisor
  command: "{{ supervisor_bin }}/supervisorctl update"
