---
- name: install MailHog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v{{ mailhog_version }}/MailHog_linux_amd64
    dest: ~/bin/mailhog
    mode: 0555

- name: deploy Mailhog cron
  cron: name="{{ mailhog_hostname }} launch mailhog at reboot" special_time=reboot job="/home/{{ ansible_user }}/bin/mailhog -hostname {{ mailhog_hostname }} -smtp-bind-addr {{ loopback_adress }}:{{ mailhog_smtp_sock }} -ui-bind-addr {{ loopback_adress }}:{{ mailhog_ui_sock }} -api-bind-addr {{ loopback_adress }}:{{ mailhog_api_sock }} > /dev/null 2>&1 &"
