---
- name: install MailHog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v{{ mailhog_version }}/MailHog_linux_amd64
    dest: ~/bin/mailhog
    mode: 0755

- name: install mhsendmail (sendmail replacement for MailHog)
  get_url:
    url: https://github.com/mailhog/mhsendmail/releases/download/v{{ mhsendmail_version }}/mhsendmail_linux_amd64
    dest: ~/bin/mhsendmail
    mode: 0755

- name: create mailhog dir
  file:
    path: ~/mailhog/data
    state: directory

- name: reload create Mailhog htpasswd
  shell: htpasswd -nbB {{ ansible_user }} {{ mailhog_password }} > $HOME/mailhog/.htpasswd

- name: send Supervisor config
  template:
    src:  supervisor.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ mailhog_name }}.conf"

- name: reload Supervisor config to launch Mailhog
  command: "{{ supervisor_bin }}/supervisorctl update"
  environment:
    PYTHON_VERSION: "{{ python_version }}"