---
- name: install MailHog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v{{ mailhog_version }}/MailHog_linux_amd64
    dest: ~/bin/mailhog
    mode: 0555

- name: send Supervisor config
  template:
    src:  supervisor.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ mailhog_name }}.conf"

- name: reload Supervisor config to launch Mailhog
  command: /home/{{ ansible_user }}/python/builds/{{ python_version }}/bin/supervisorctl update
