---
- name: ensure needed folders exist
  file: path={{ elastic_folder }}/{{ item }} state=directory follow=yes
  with_items:
    - log
    - data

- name: be sure to remove previous install
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ elastic_folder }}/{{ elastic_name }}"
    - "{{ supervisor_folder }}/conf.d/{{ elastic_name }}.conf"

- name: reload Supervisor config to update ElasticSearch status
  command: "{{ supervisor_bin }}/supervisorctl update"

- name: set up Java path for version < 5.0.0
  set_fact: java_home="/usr/lib/jvm/java-7-openjdk-amd64/"
  when: ( elastic_version < "5.0.0" )

- name: set up Java path for version > 4.x
  set_fact: java_home="/usr/alwaysdata/java/8.0.41/"
  when: not ( elastic_version < "5.0.0" )

- name: download ElasticSearch for version < 5.0.0
  get_url:
    url: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/{{ elastic_version }}/elasticsearch-{{ elastic_version }}.tar.gz
    dest: "{{ elastic_folder }}/elasticsearch-{{ elastic_version }}.tar.gz"
  when: ( elastic_version < "5.0.0" )

- name: download ElasticSearch for version > 4.x
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}.tar.gz
    dest: "{{ elastic_folder }}/elasticsearch-{{ elastic_version }}.tar.gz"
  when: (not ( elastic_version < "5.0.0" )) and ( elastic_version < "7.0.0" )

- name: download ElasticSearch for version > 7.x
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz
    dest: "{{ elastic_folder }}/elasticsearch-{{ elastic_version }}.tar.gz"
  when: not ( elastic_version < "7.0.0" )

- name: extract ElasticSearch
  unarchive:
    src: "{{ elastic_folder }}/elasticsearch-{{ elastic_version }}.tar.gz"
    dest: "{{ elastic_folder }}/"
    remote_src: True

- name: move ElasticSearch folder to this final destination
  shell: cp -rTf {{ elastic_folder }}/elasticsearch-{{ elastic_version }} {{ elastic_folder }}/{{ elastic_name }} && rm -rf {{ elastic_folder }}/elasticsearch-{{ elastic_version }}

- name: check if ElasticFence plugin is installed for version < 5.0.0
  command: "{{ elastic_folder }}/{{ elastic_name }}/bin/plugin list"
  register: es_plugin_list
  when: ( elastic_version < "5.0.0" )
  environment:
    JAVA_HOME: "{{ java_home }}"

- name: install ElasticFence plugin for version < 5.0.0
  command: "{{ elastic_folder }}/{{ elastic_name }}/bin/plugin install https://raw.githubusercontent.com/elasticfence/elasticsearch-http-user-auth/{{ elastic_version }}/jar/elasticfence-{{ elastic_version }}-SNAPSHOT.zip"
  when: ( elastic_version < "5.0.0" ) and ( "elasticfence" not in es_plugin_list.stdout )
  environment:
    JAVA_HOME: "{{ java_home }}"

- name: install ElasticFence plugin for version > 4.x and < 5.6
  command: "{{ elastic_folder }}/{{ elastic_name }}/bin/elasticsearch-plugin install https://raw.githubusercontent.com/elasticfence/elasticsearch-http-user-auth/{{ elastic_version }}/jar/elasticfence-{{ elastic_version }}-SNAPSHOT.zip"
  when: not ( elastic_version < "5.0.0" ) and ( elastic_version < "5.1.3" )
  environment:
    JAVA_HOME: "{{ java_home }}"

- name: install ElasticHead plugin for version < 5.0.0 (version > 4.x do not support site plugin)
  command: "{{ elastic_folder }}/{{ elastic_name }}/bin/plugin install mobz/elasticsearch-head"
  when: ( elastic_version < "5.0.0" ) and ( "head" not in es_plugin_list.stdout )
  environment:
    JAVA_HOME: "{{ java_home }}"

- name: send ElasticSearch config for ElasticFence
  template:
    src:  elasticsearch_elasticfence.yml.j2
    dest: "{{ elastic_folder }}/{{ elastic_name }}/config/elasticsearch.yml"
  when: ( elastic_version < "5.1.3" )

- name: send noauth config for ElasticSearch ( 6.3.0 > version > 5.1.3)
  template:
    src:  elasticsearch_noauth.yml.j2
    dest: "{{ elastic_folder }}/{{ elastic_name }}/config/elasticsearch.yml"
  when: elastic_version > "5.1.3" and elastic_version < "6.3.0"

- name: send noauth config and disable x-pack feature for ElasticSearch (version > 6.3.0)
  template:
    src:  elasticsearch_noauth_noxpack.yml.j2
    dest: "{{ elastic_folder }}/{{ elastic_name }}/config/elasticsearch.yml"
  when: (not ( elastic_version < "6.3.0" )) and ( elastic_version < "7.0.0" )

- name: send noauth config and disable x-pack feature for ElasticSearch (version > 6.3.0)
  template:
    src:  elasticsearch_v7.yml.j2
    dest: "{{ elastic_folder }}/{{ elastic_name }}/config/elasticsearch.yml"
  when: not ( elastic_version < "7.0.0")

- name: send Supervisor config for version < 5.0.0
  template:
    src:  elasticsearch.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ elastic_name }}.conf"
  when: ( elastic_version < "5.0.0" )

- name: send Supervisor config for version >= 5
  template:
    src:  elasticsearchv5.conf.j2
    dest: "{{ supervisor_folder }}/conf.d/{{ elastic_name }}.conf"
  when: not ( elastic_version < "5.0.0" )

- name: reload Supervisor config to launch ElasticSearch
  command: "{{ supervisor_bin }}/supervisorctl update"

- name: Wait 300 seconds max for ElasticSearch to be ready
  wait_for:
    host: "{{ loopback_adress }}"
    port: "{{ elastic_port }}"
    delay: 3
  when: not ( elastic_version < "5.1.3")

- name: Create superuser (user x-pack.security version > 6.3.0)
  command: "{{ elastic_folder }}/{{ elastic_name }}/bin/elasticsearch-users useradd -roles superuser -p {{ elastic_pass }} {{ elastic_user }}"
  environment:
    PATH: "{{ java_home }}/bin:/home/{{ ansible_user }}/bin/:/home/{{ ansible_user }}/.local/bin:/usr/local/bin:/usr/bin:/bin"
  when: not ( elastic_version < "7.0.0")
