python_version: 2.7.15
python_folder: "/home/{{ ansible_user }}/python"
python_need_compilation: false
python_native_version:
  - "2.4.6"
  - "2.5.6"
  - "2.6.9"
  - "2.7.15"
  - "3.3.7"
  - "3.4.9"
  - "3.5.6"
  - "3.6.6"
  - "3.6.7"
  - "3.7.1"