python_version: 3.7.7
python_folder: "/home/{{ ansible_user }}/python"
python_need_compilation: false
python_native_version:
  - "2.4.6"
  - "2.5.6"
  - "2.6.9"
  - "2.7.17"
  - "2.7.18"
  - "3.3.7"
  - "3.4.10"
  - "3.5.9"
  - "3.5.10"
  - "3.6.10"
  - "3.6.11"
  - "3.6.12"
  - "3.6.13"
  - "3.6.14"
  - "3.6.15"
  - "3.7.7"
  - "3.7.8"
  - "3.7.9"
  - "3.7.10"
  - "3.7.11"
  - "3.7.12"
  - "3.8.2"
  - "3.8.3"
  - "3.8.4"
  - "3.8.5"
  - "3.8.6"
  - "3.8.7"
  - "3.8.8"
  - "3.8.9"
  - "3.8.10"
  - "3.8.11"
  - "3.8.12"
  - "3.9.0"
  - "3.9.1"
  - "3.9.2"
  - "3.9.3"
  - "3.9.4"
  - "3.9.5"
  - "3.9.6"
  - "3.9.7"
  - "3.9.8"
  - "3.9.9"
  - "3.10.0"
