---
- name: be sure to remove previous install
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ filebeat_folder }}/{{ filebeat_name }}"
    - "{{ filebeat_folder }}/tmp"
    - "{{ supervisor_folder }}/conf.d/{{ filebeat_name }}.conf"

- name: ensure needed folders exist
  file: path={{ filebeat_folder }}/{{ item }} state=directory follow=yes
  with_items:
    - log
    - data
    - tmp

- name: reload Supervisor config to update FileBeat status
  command: "{{ supervisor_bin }}/supervisorctl update"

- name: download FileBeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz
    dest: "{{ filebeat_folder }}/tmp/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"

- name: extract FileBeat
  unarchive:
    src: "{{ filebeat_folder }}/tmp/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
    dest: "{{ filebeat_folder }}/tmp/"
    remote_src: True

- name: remove install ressources
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ filebeat_folder }}/tmp/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"

- name: move FileBeat folder to this final destination
  shell: mv {{ filebeat_folder }}/tmp/filebeat-{{ filebeat_version }}-linux-x86_64 {{ filebeat_folder }}/{{ filebeat_name }}

- name: send FileBeat config
  template:
    src:  filebeat.yml
    dest: "{{ filebeat_folder }}/{{ filebeat_name }}/filebeat.yml"

- name: send Supervisor config
  template:
    src:  filebeat.conf
    dest: "{{ supervisor_folder }}/conf.d/{{ filebeat_name }}.conf"

- name: reload Supervisor config to launch ElasticSearch
  command: "{{ supervisor_bin }}/supervisorctl update"
