---
- name: install wkhtmltopdf
  unarchive:
    src: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/{{ wkhtmltopdf_version }}/wkhtmltox-{{ wkhtmltopdf_version }}_linux-generic-amd64.tar.xz
    extra_opts: [--strip-components=2]
    dest: ~/bin/
    exclude: ["wkhtmltox/include","wkhtmltox/lib","wkhtmltox/share"]
    mode: 0755
    remote_src: yes

