---
- name: check if Node need specific install
  set_fact: node_native=False
  when: (node_version not in node_native_version)

- name: install NodeEnv
  git:
    repo: https://github.com/OiNutter/nodenv.git
    dest: ~/.nodenv

- name: set NodeEnv local env variable
  lineinfile:
    create=yes
    dest=~/.bash_profile
    line="{{ item }}"
  with_items:
    - export PATH="$HOME/.nodenv/bin:$PATH"
    - eval "$(nodenv init -)"

- name: add node-build plugin to nodeenv
  git:
    repo: https://github.com/OiNutter/node-build.git
    dest: ~/.nodenv/plugins/node-build

- name: install nodejs
  command: chdir=~/ {{item}}
  with_items:
    - ~/.nodenv/bin/nodenv install -s {{ node_version }}
    - ~/.nodenv/bin/nodenv rehash
  when: not node_native

- name: set nodejs {{ node_version }} as default version when not native
  command: chdir=~/ {{item}}
  with_items:
    - ~/.nodenv/bin/nodenv global {{ node_version }}
  when: node_default and not node_native

- name: set nodejs {{ node_version }} as default version when not native
  command: chdir=~/ {{item}}
  with_items:
    - ~/.nodenv/bin/nodenv global system
  when: node_default and node_native

- name: set nodejs {{ node_version }} ENV var when native
  lineinfile:
    create: yes
    dest: ~/.bash_profile
    line: export NODEJS_VERSION={{ node_version }}
  when: node_default and node_native

  