---
- name: ensure local logrotate folder exist
  file: path=~/logrotate state=directory

- name: ensure local logrotate config exist
  file: path=~/logrotate/logrotate.conf state=touch

- name: send logrotate config sample
  template:
    src:  logrotate.conf_sample.j2
    dest: ~/logrotate/logrotate.conf_sample.j2

- name: deploy logrotate cron
  cron:
    name: launch logrotate
    special_time: daily
    job: /usr/sbin/logrotate /home/{{ ansible_user }}/logrotate/logrotate.conf -s /home/{{ ansible_user }}/logrotate/status >/dev/null 2>&1
