---
- name: ensure all Supervisor working folders exist
  file: path="{{ item }}" state=directory follow=yes
  with_items:
    - "{{ supervisor_folder }}/conf.d"
    - "{{ supervisor_folder }}/log"
    - "{{ supervisor_folder }}/run"

- name: install Supervisor
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
    executable: pip
  environment:
    PATH: "{{ ansible_env.PATH }}"
    PYTHON_VERSION: "{{ python_version }}"

- name: send Supervisor configuration file
  template:
    src:  supervisord.conf.j2
    dest: "{{ supervisor_folder }}/supervisord.conf"

- name: ensure Supervisor configuration folders exist
  file: path="/home/{{ ansible_user }}/.local/etc" state=directory

- name: link Supervisor configuration file to default path
  file:
    src: "{{ supervisor_folder }}/supervisord.conf"
    dest: /home/{{ ansible_user }}/.local/etc/supervisord.conf
    state: link

- name: register supervisor bin path
  set_fact:
    supervisor_bin: /home/{{ ansible_user }}/.local/bin

- name: check supervisor status
  command: "{{ supervisor_bin }}/supervisorctl status"
  register: supervisor_status
  ignore_errors: yes

- name: start Supervisor if not already running
  command: "{{ supervisor_bin }}/supervisord"
  when: '("refused connection" in supervisor_status.stdout) or ("no such file" in supervisor_status.stdout)'

- name: ensure Supervisor start at boot
  cron:
    name: launch Supervisor
    special_time: reboot
    job: "{{ supervisor_bin }}/supervisord"

- name: ensure Supervisor stay alive
  cron:
    name: relaunch Supervisor if it's missing
    minute: "*"
    hour: "*"
    job: "pgrep supervisord > /dev/null || {{ supervisor_bin }}/supervisord"