---
- name: be sure to remove previous install
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kibana_folder }}/{{ kibana_name }}"

- name: ensure needed folders exist
  file: 
    path: "{{ item }}"
    state: directory
    follow: yes
  with_items:
    - "{{ kibana_folder }}"
    - "{{ kibana_folder }}/{{ kibana_name }}"
    - "{{ kibana_folder }}/tmp"

- name: reload Supervisor config to update Kibana status
  command: "{{ supervisor_bin }}/supervisorctl update"

- name: download Kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz
    dest: "{{ kibana_folder }}/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"

- name: extract Kibana
  unarchive:
    src: "{{ kibana_folder }}/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_folder }}/{{ kibana_name }}"
    extra_opts: [--strip-components=1]
    remote_src: True

- name: remove install ressources
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ kibana_folder }}/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"

- name: send Kibana server config
  template:
    src:  kibana.yml
    dest: "{{ kibana_folder }}/{{ kibana_name }}/config/kibana.yml"

- name: send Supervisor config
  template:
    src:  supervisor-kibana.conf
    dest: "{{ supervisor_folder }}/conf.d/{{ kibana_name }}.conf"

- name: reload Supervisor config to launch ElasticSearch
  command: "{{ supervisor_bin }}/supervisorctl update"
