node_version: 6.14.4
node_default: True
node_native: True
node_native_version:
  - "6.14.1"
  - "6.14.2"
  - "6.14.3"
  - "6.14.4"
  - "8.11.1"
  - "8.11.2"
  - "8.11.3"
  - "8.11.4"
  - "8.12.0"
  - "9.11.2"
  - "10.1.0"
  - "10.6.0"
  - "10.9.0"
  - "10.12.0"
  - "10.13.0"
  - "11.0.0"
  - "11.1.0"