magento_version: magento-mirror-1.9.3.4
magento_folder: /home/{{ ansible_user }}/magento
magento_baseurl: "http://{{ ansible_user }}.occitech.eu"
magento_dbhost: mysql-{{ ansible_user }}.occitech.eu
magento_currency: EUR
magento_locale: fr_FR
magento_timezone: Europe/paris
magento_use_rewrites: yes
magento_session_save: files
magento_admin_username: "{{ ansible_user }}"
magento_admin_firstname: "{{ ansible_user }}"
magento_admin_lastname: occitech.eu
magento_admin_password: tobechang3d!
magento_admin_frontname: "admin_{{ ansible_user }}"
magento_admin_email: "{{ ansible_user }}@occitech.eu"
magento_encryption_key: "{{ 9999999999999999999999 | random }}"
