---

- name: checkout Odoo source
  git:
    repo: https://github.com/odoo/odoo.git
    dest: "{{ odoo_folder }}/src"
    depth: 1
    version: "{{ odoo_version }}"

- name: install odoo requirements
  shell: chdir="{{ odoo_folder }}/src" {{ item }}
  with_items:
    - pip install -r requirements.txt
    - npm install -g less
  args:
     executable: /bin/bash
  environment:
    PYTHON_VERSION: "{{ python_version }}"

- name: duplicate launch script
  copy:
    src: "{{ odoo_folder }}/src/odoo-bin"
    dest: "{{ odoo_folder }}/src/odoo-run"
    remote_src: yes

- name: update duplicated launch script to work on our hosting
  replace: 
    path: "{{ odoo_folder }}/src/odoo-run"
    regexp: '\/usr\/bin\/env python3'
    replace: '/usr/bin/env python'
    backup: yes

- name: fix executable permission
  file:
    path: "{{ odoo_folder }}/src/odoo-run"
    mode: 0755