---
- name: be sure to remove previous install
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ logstash_folder }}/{{ logstash_name }}"
    - "{{ logstash_folder }}/tmp"
    - "{{ supervisor_folder }}/conf.d/{{ logstash_name }}.conf"

- name: ensure needed folders exist
  file: 
    path: "{{ logstash_folder }}/{{ item }}"
    state: directory
    follow: yes
  with_items:
    - "config"
    - "data"
    - "data/{{ logstash_name }}"
    - "log"
    - "log/{{ logstash_name }}"
    - "src"
    - "src/{{ logstash_name }}"
    - "tmp"

- name: reload Supervisor config to update Logstash status
  command: "{{ supervisor_bin }}/supervisorctl update"

- name: download Logstash
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz
    dest: "{{ logstash_folder }}/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"

- name: extract Logstash
  unarchive:
    src: "{{ logstash_folder }}/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
    dest: "{{ logstash_folder }}/src/{{ logstash_name }}"
    extra_opts: [--strip-components=1]
    remote_src: True

- name: remove install ressources
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ logstash_folder }}/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"

- name: send Logstash logging config
  template:
    src:  logstash.conf
    dest: "{{ logstash_folder }}/config/{{ logstash_name }}.conf"


- name: send Logstash server config
  template:
    src:  logstash.yml
    dest: "{{ logstash_folder }}/src/{{ logstash_name }}/config/logstash.yml"

- name: send Supervisor config
  template:
    src:  supervisor-logstash.conf
    dest: "{{ supervisor_folder }}/conf.d/{{ logstash_name }}.conf"

- name: reload Supervisor config to launch ElasticSearch
  command: "{{ supervisor_bin }}/supervisorctl update"
